routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\GroupController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\UserController;
// use App\Http\Controllers\GroupController;
use Illuminate\Support\Facades\Route;
use Symfony\Component\CssSelector\XPath\Extension\FunctionExtension;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//Login
Route::get('/', [AuthController::class, 'login'])->name('login');
Route::post('/checklogin', [AuthController::class, 'postLogin'])->name('admin.checklogin');
Route::get('/forget-password', [UserController::class, 'forget_password'])->name('forget-password');
Route::post('/sendmail', [UserController::class, 'sendMail'])->name('sendmail');

Route::prefix('/')->middleware(['auth', 'preventBackHistory'])->group(function () {
    Route::get('admin', [AuthController::class, 'home'])->name('trangchu');
    Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

    // Categoryy
    Route::group(['prefix' => 'categories'], function () {
        Route::get('/trash', [CategoryController::class, 'getTrashed'])->name('categories.trash');
        Route::get('/restore/{id}', [CategoryController::class, 'restore'])->name('categories.restore');
        Route::delete('/deleteforever/{id}', [CategoryController::class, 'deleteforever'])->name('categories.deleteforever');
        });
    Route::resource('categories',\App\Http\Controllers\CategoryController::class);
   
    // Rooms
    Route::group(['prefix' => 'rooms'], function () {
        Route::get('/trash', [RoomController::class, 'getTrashed'])->name('rooms.trash');
        Route::get('/restore/{id}', [RoomController::class, 'restore'])->name('rooms.restore');
        Route::delete('/deleteforever/{id}', [RoomController::class, 'deleteforever'])->name('rooms.deleteforever');
        });
    Route::resource('rooms',\App\Http\Controllers\RoomController::class);
    //xuất file excel rooms
    Route::get('/export-rooms', [RoomController::class, 'export'])->name('rooms.export');
    // Customers
    Route::get('/customers', [CustomerController::class, 'index'])->name('customers.index');
    // Orders
    Route::group(['prefix' => 'orders'], function () {
        Route::get('/', [OrderController::class, 'index'])->name('orders.index');
        Route::get('/detail/{id}', [OrderController::class, 'show'])->name('orders.detail');
        Route::get('/create', [OrderController::class, 'create'])->name('orders.create');
        Route::post('/store', [OrderController::class, 'store'])->name('orders.store');
    });
    //xuất file excel orders
    Route::get('/export-orders', [OrderController::class, 'export'])->name('orders.export');

    Route::resource('users',\App\Http\Controllers\UserController::class);
    Route::resource('groups',\App\Http\Controllers\GroupController::class);
    Route::group(['prefix'=>'groups'], function(){
    Route::put('/updateRoles/{id}', [GroupController::class, 'updateRoles'])->name('groups.updateRoles');

});
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;
    protected $table ='users';
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'created_at',
        'address',
        'image',
        'phone',
        'gender',
        'birthday',
        'group_id'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function group()
    {
        return $this->belongsTo(Group::class, 'group_id', 'id');
    }
    public function hasPermission($role_name)
    {
        // dd('model user');
        $user_roles = isset($this->group->roles) ? $this->group->roles->pluck('name')->toArray() : [];
        if (in_array($role_name, $user_roles)) {
            return true;
        } else {
            return false;
        }
    }
    public function scopeSearch($query, $term)
    {
        if ($term) {
            $query->where('name', 'like', '%' . $term . '%')
                ->orWhere('id', 'like', '%' . $term . '%');
        }
        return $query;
    }
}

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreUserRequest;
use App\Http\Resources\UserResource;
use App\Services\Interfaces\UserServiceInterface;
use Illuminate\Http\Request;

class UserController extends Controller
{
    protected $userService;
    // protected $groupService;

    public function __construct(
        UserServiceInterface $userService
    ) {
        $this->userService = $userService;
    }
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $items = $this->userService->all($request);
        return UserResource::collection($items);
    }

    /**
     * Show the form for creating a new resource.
     */

    public function store(StoreUserRequest $request)
    { 
        $data = $request->except(['_token', '_method']);
        $this->userService->store($data);
        return response()->json([
            'success' => true,
        ]);
    }

    public function show(string $id)
    {
        $item = $this->userService->find($id);
        return new UserResource($item);
    }
    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $data = $request->except(['_token', '_method']);
        $this->userService->update($data, $id);
        return response()->json([
            'success' => true,
        ]);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $this->userService->destroy($id);
        response()->json([
            'success' => true,
        ]);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ChangePassWordByMailRequest;
use App\Http\Requests\StoreUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Jobs\SendEmail;
use App\Models\User;
use App\Models\Group;
use Illuminate\Http\Request;
use App\Services\Interfaces\UserServiceInterface;
// use App\Repositories\Interfaces\GroupServiceInterface;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Str;

class UserController extends Controller
{
    protected $userService;
    // protected $groupService;

    public function __construct(
        UserServiceInterface $userService
        // GroupServiceInterface $groupService
    )
    {
        $this->userService = $userService;
        // $this->groupService = $groupService;
    }
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $this->authorize('viewAny', User::class);
        $items = $this->userService->all($request);
        $groups = group::get();
        return view('users.index', compact('items','groups'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $this->authorize('create', User::class);
        $items = User::all();
        $groups = Group::all();
        return view('users.create', compact('items', 'groups'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreUserRequest $request)
    {

        $data = $request->except(['_token', '_method']);
        $this->userService->store($data);
        toast('Thêm Thành Công!', 'success', 'top-right');
        return redirect()->route('users.index');
    }


    public function show($id)
    {
        $Users = User::get();
        $items = $this->userService->find($id);
        return view('users.show', compact('items', 'Users'));
    }


    public function edit($id)
    {
        $this->authorize('update', User::class);
        $groups = Group::all();
        $item = $this->userService->find($id);
        // dd($item);
        return view('users.edit', compact('item', 'groups'));
    }


    public function update(UpdateUserRequest $request, $id)
    {
        // dd(123);
        $data = $request->except(['_token', '_method']);
        $this->userService->update($id, $data);
        toast('Sửa Thành Công!', 'success', 'top-right');
        return redirect()->route('users.index');
    }


    public function destroy($id)
    {
        $this->authorize('delete', User::class);
        $this->userService->destroy($id);
        toast('Xóa Thành Công!', 'success', 'top-right');
        return redirect()->route('users.index');
    }

    public function forget_password()
    {
        // dd(987654);
        return view('emails.fogotpass');
    }
    public function sendMail(Request $request){
// dd($request->email);
        $user = DB::table('users')->where('email', $request->email)->first();
        if(!$user){
            toast('Email: ' . $request->email.'<br> Không tồn tại', 'error', 'top-right');
            return back()->withInput();
        }
        if($request->email == $user->email){
            try {
            $password = Str::random(6);
            $user = User::find($user->id);
            $user->password= bcrypt($password);
            $user->save();
            $datas = [
                'name' => $user->name,
                'password' => $password,
                'email' => $user->email,
                'check' => 'changepassword',
            ];
            SendEmail::dispatch($datas)->delay(now()->addMinute(1));
            toast('Gửi yêu cầu mật khẩu!'.'<br>'.' Thành Công', 'success', 'top-right');
            return back()->withInput();
        } catch (\Exception $e) {
            Log::error('message: ' . $e->getMessage() . 'line: ' . $e->getLine() . 'file: ' . $e->getFile());
            toast('Gửi yêu cầu mật khẩu!'.'<br>'.' Không thành Công', 'error', 'top-right');
            return back()->withInput();
        }
        } else{
            toast('Email: ' . $request->emails. '<br> Không tồn tại', 'error', 'top-right');
            return back()->withInput();
            }
    }
}

resources/views/users/create.blade.php
@extends('layouts.master')
@section('content')
    <div class="page-header">
        <h3 class="page-title">Thêm Nhân Viên</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Trang chủ /</a></li>
                <form action="{{ route('users.store') }}" method='post' enctype="multipart/form-data">
                    <li class="breadcrumb-item active" aria-current="page"> Thêm Nhân Viên </li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <form class="forms-sample">
                        @csrf
                        <div class="form-group">
                            <label for="exampleInputName1">Tên nhân viên </label>
                            <input type="text" name='name' value="{{ old('name') }}" class="form-control"
                                id="exampleInputName1" placeholder="Tên">
                            @error('name')
                                <p class="text text-danger ">{{ $message }}</p>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail3">Email</label>
                            <input type="email" name="email" value="{{ old('email') }}" class="form-control"
                                id="exampleInputEmail3" placeholder="Email">
                            @error('email')
                                <p class="text text-danger ">{{ $message }}</p>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword4">Mật khẩu</label>
                            <input type="password" name='password' value="{{ old('password') }}" class="form-control"
                                id="exampleInputPassword4" placeholder="Password">
                            @error('password')
                                <p class="text text-danger ">{{ $message }}</p>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label class="form-label">Trao quyền</label>
                            <select name="group_id" id="" class="form-control">
                                <option value="{{ old('group_id') }}">--Vui lòng chọn--</option>
                                @foreach ($groups as $group)
                                    <option value="{{ $group->id }}">{{ $group->name }} </option>
                                @endforeach
                            </select>
                            @error('group_id')
                                <p class="alert alert-danger">{{ $message }}</p>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label>Ảnh</label>
                            <input type="file" name="image" class="file-upload-default" value="{{ old('image') }}">
                            <div class="input-group col-xs-12">
                                <input type="file" name="image" id="Inputimage"class="form-control file ">
                                @error('image')
                                    <p class="text text-danger ">{{ $message }}</p>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputCity1">Ngày tham gia</label>
                            <input type="date" class="form-control" name="created_at" id="exampleInputEmail1"
                                placeholder="Location" value="{{ old('created_at') }}">
                            @error('created_at')
                                <p class="text text-danger ">{{ $message }}</p>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputName1">Địa chỉ</label>
                            <input type="address" class="form-control" name="address" id="exampleInputEmail1"
                                aria-describedby="emailHelp" value="{{ old('address') }}">
                            @error('address')
                                <p class="text text-danger ">{{ $message }}</p>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputName1">Ngày sinh</label>
                            <input type="date" class="form-control" name="birthday" id="exampleInputEmail1"
                                aria-describedby="emailHelp" value="{{ old('birthday') }}">
                            @error('birthday')
                                <p class="text text-danger ">{{ $message }}</p>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputName1">Giới Tính<abbr name="Trường bắt buộc">*</abbr></label>
                            <select name="gender" id="" class="form-control" value="{{ old('gender') }}">
                                <option value="">--Vui lòng chọn--</option>
                                <option value="1">Nam</option>
                                <option value="2">Nữ</option>
                                <option value="Khác">Khác</option>
                            </select>
                            @error('gender')
                                <p class="text text-danger">{{ $message }}</p>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputName1">Số điện thoại</label>
                            <input type="phone" class="form-control" name="phone" value="{{ old('phone') }}">
                            @error('phone')
                                <p class="text text-danger ">{{ $message }}</p>
                            @enderror
                        </div>
                        <button type="submit" class="btn btn-primary mr-2"> Thêm </button>
                        <a href="{{ route('users.index') }}" class="btn btn-light">Quay lại</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.master')
@section('content')
 @include('sweetalert::alert')
    <div class="page-header">
        <h3 class="page-title">Chỉnh Sửa nhân viên </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('trangchu')}}">Trang chủ</a></li>
                <li class="breadcrumb-item active" aria-current="page"> Chỉnh Sửa nhân viên </li>
                <form  action="{{route('users.update',[$item->id])}}" method="POST" enctype="multipart/form-data">
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <form  action="{{route('categories.update',[$item->id])}}" method="POST" enctype="multipart/form-data">
                        @method('PUT')
                        @csrf
                        <div class="form-group">
                            <label for="exampleInputName1">Tên nhân viên </label>
                            <input name="name" type="text" value='{{$item->name}}' class="form-control" >
                            @error('name')
                                <p class="text text-danger ">{{ $message }}</p>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputName1">Email </label>
                            <input type="email" name="email" value='{{$item->email}}' class="form-control">
                            @error('email')
                            <p class="text text-danger ">{{ $message }}</p>
                        @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputName1">Mật khẩu </label>
                            <input type="password" name="password" class="form-control">
                            @error('password')
                            <p class="text text-danger ">{{ $message }}</p>
                        @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputName1">Ngày tham gia </label>
                            <input type="date" name="created_at" value='{{$item->created}}' class="form-control">
                            @error('created_at')
                            <p class="text text-danger ">{{ $message }}</p>
                        @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputName1">Địa chỉ</label>
                            <input type="text" name="address" value='{{$item->address}}' class="form-control">
                            @error('address')
                            <p class="text text-danger ">{{ $message }}</p>
                        @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputName1">Điện thoại</label>
                            <input type="phone" name="phone" value='{{$item->phone}}' class="form-control">
                            @error('phone')
                            <p class="text text-danger ">{{ $message }}</p>
                        @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputName1">Ngày sinh</label>
                            <input type="date" name="birthday" value='{{$item->birthday}}' class="form-control">
                            @error('birthday')
                            <p class="text text-danger ">{{ $message }}</p>
                        @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1" class="form-label">Ảnh</label>
                            <input type="file" class="form-control" name="image" value='{{$item->image}}'>
                            <img type="hidden" width="120px" height="120px" id="blah1"
                                                src="{{ $item->image}}" alt="" />
                        </div>
                        <div class="form-group">
                            <label for="exampleInputName1">Giới tính</label>
                            <select name="gender" id="" class="form-control">
                                <option value="1" @selected($item->gender == 1)>Nam</option>
                                <option value="2" @selected($item->gender == 2)>Nữ</option>
                                <option value="3"@selected($item->gender == 3)>Khác</option>
                                @error('gender')
                                <p class="text text-danger ">{{ $message }}</p>
                            @enderror
                              </select>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Trao quyền</label>
                             <select name="group_id" class="custom-select">
                              @foreach($groups as $key => $value)
                              <option {{ $item->group_id==$value->id ? 'selected' : '' }} value="{{$value->id}}">{{$value->name}}</option>
                              @endforeach
                              @error('group_id')
                              <p class="text text-danger ">{{ $message }}</p>
                          @enderror
                            </select>

                          </div>
                        <input type="submit" class="btn btn-info" value="Cập nhật" >
                        <a href="{{route('users.index')}}" class="btn btn-light">Quay lại</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.master')
@section('content')
    <div class="page-header">
        <h3 class="page-title">Quản lý nhân viên </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('trangchu') }}">Trang chủ</a></li>
                <li class="breadcrumb-item active" aria-current="page"> Quản lý nhân viên </li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-header">
                    <form action="" method="get">
                        <div class="row mb-2">
                         @if (Auth::user()->hasPermission('User_create'))
                            <div class="col">
                                <a href="{{ route('users.create') }}" class="btn btn-info">Thêm mới</a>
                            </div>
                        @endif
                        </div>
                        <div class="row">
                            <div class="col">
                                <input type="text" placeholder="Nhập ID" class="form-control" value="{{ request()->id }}"
                                    name="id">
                            </div>
                            <div class="col">
                                <input type="text" placeholder="Nhập tên" class="form-control"
                                    value="{{ request()->name }}" name="name">
                            </div>
                            <div class="col">
                                <select name="group_id" id="" class="form-control">
                                    <option value="">--Vui lòng chọn--</option>
                                    @foreach ($groups as $group)
                                        <option value="{{ $group->id }}">{{ $group->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col">
                                <button type="submit" class="btn btn-info"> Tìm </button>
                                <a href="{{ route('groups.index') }}" type="submit" class="btn btn-secondary">Đặt lại</a>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>STT</th>
                                    <th>Tên Nhân viên</th>
                                    <th>Ảnh</th>
                                    <th>Số điện thoại</th>
                                    <th>Nhóm nhân viên </th>
                                    <th>Hành động </th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    @foreach ($items as $key => $item)
                                        <td>{{ ++$key }}</td>
                                        <td>{{ $item->name }}</td>
                                        <td><a href="{{ route('users.show', $item->id) }}"><img
                                                    style="width:120px; height:100px" src="{{ asset($item->image) }}"
                                                    alt=""></a></td>
                                        <td>{{ $item->phone }}</td>
                                        <td> {{ isset($item->group->name) ? $item->group->name : 'chưa phân quyền' }}</td>
                                        @if (Auth::user()->hasPermission('User_update') || Auth::user()->hasPermission('User_delete'))
                                            <td>
                                                @if (Auth::user()->hasPermission('User_update'))
                                                <form action="{{ route('users.destroy', [$item->id]) }}" method="post">
                                                    @method('DELETE')
                                                    @csrf
                                                    <a href="{{ route('users.edit', $item['id']) }}"
                                                        class="btn btn-info">Sửa</a>
                                                @endif
                                                @if(Auth::user()->hasPermission('User_delete'))
                                                    <button
                                                        onclick="return confirm('Bạn có muốn xóa  này không?');"class="btn btn-danger">Xóa</button>
                                                @endif
                                            </td>
                                        @endif
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <nav class="float-right">
                        {{ $items->links() }}
                    </nav>
                </div>
            </div>
        </div>
    </div>
@endsection