routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\GroupController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\UserController;
// use App\Http\Controllers\GroupController;
use Illuminate\Support\Facades\Route;
use Symfony\Component\CssSelector\XPath\Extension\FunctionExtension;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//Login
Route::get('/', [AuthController::class, 'login'])->name('login');
Route::post('/checklogin', [AuthController::class, 'postLogin'])->name('admin.checklogin');
Route::get('/forget-password', [UserController::class, 'forget_password'])->name('forget-password');
Route::post('/sendmail', [UserController::class, 'sendMail'])->name('sendmail');

Route::prefix('/')->middleware(['auth', 'preventBackHistory'])->group(function () {
    Route::get('admin', [AuthController::class, 'home'])->name('trangchu');
    Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

    // Categoryy
    Route::group(['prefix' => 'categories'], function () {
        Route::get('/trash', [CategoryController::class, 'getTrashed'])->name('categories.trash');
        Route::get('/restore/{id}', [CategoryController::class, 'restore'])->name('categories.restore');
        Route::delete('/deleteforever/{id}', [CategoryController::class, 'deleteforever'])->name('categories.deleteforever');
        });
    Route::resource('categories',\App\Http\Controllers\CategoryController::class);
   
    // Rooms
    Route::group(['prefix' => 'rooms'], function () {
        Route::get('/trash', [RoomController::class, 'getTrashed'])->name('rooms.trash');
        Route::get('/restore/{id}', [RoomController::class, 'restore'])->name('rooms.restore');
        Route::delete('/deleteforever/{id}', [RoomController::class, 'deleteforever'])->name('rooms.deleteforever');
        });
    Route::resource('rooms',\App\Http\Controllers\RoomController::class);
    //xuất file excel rooms
    Route::get('/export-rooms', [RoomController::class, 'export'])->name('rooms.export');
    // Customers
    Route::get('/customers', [CustomerController::class, 'index'])->name('customers.index');
    // Orders
    Route::group(['prefix' => 'orders'], function () {
        Route::get('/', [OrderController::class, 'index'])->name('orders.index');
        Route::get('/detail/{id}', [OrderController::class, 'show'])->name('orders.detail');
        Route::get('/create', [OrderController::class, 'create'])->name('orders.create');
        Route::post('/store', [OrderController::class, 'store'])->name('orders.store');
    });
    //xuất file excel orders
    Route::get('/export-orders', [OrderController::class, 'export'])->name('orders.export');

    Route::resource('users',\App\Http\Controllers\UserController::class);
    Route::resource('groups',\App\Http\Controllers\GroupController::class);
    Route::group(['prefix'=>'groups'], function(){
    Route::put('/updateRoles/{id}', [GroupController::class, 'updateRoles'])->name('groups.updateRoles');

});
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{

    use HasFactory;
    protected $table ='categories';
    use HasFactory,SoftDeletes;
    protected $fillable = ['id','name','image'];

    public function rooms()
    {
        return $this->hasMany(Room::class);
    }
    public function scopeSearch($query, $term)
    {
        if ($term) {
            $query->where('id', 'like', '%' . $term . '%')
                ->orWhere('name', 'like', '%' . $term . '%');
        }
        return $query;

    }
}

app/Http/Controllers/Api/CategoryController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreCategoryRequest;
use App\Http\Resources\CategoryResource;
use App\Http\Resources\RoomResource;
use App\Services\Interfaces\CategoryServiceInterface;
use App\Services\Interfaces\RoomServiceInterface;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    protected $categoryService;
    protected $roomService;
    public function __construct(
        CategoryServiceInterface $categoryService,
        RoomServiceInterface $roomService
        )
    {
        $this->categoryService = $categoryService;
        $this->roomService = $roomService;
    }
    public function index(Request $request)
    {
        $items = $this->categoryService->all($request);
        return CategoryResource::collection( $items);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreCategoryRequest $request)
    {
        $this->categoryService->store($request);
        response()->json()([
            'success'=>true,
        ]);

    }

    /**
     * Display the specified resource.
     */
    public function show(string $id ,Request $request)
    {
        $request->category_id = $id;
        $request->id = 0;
        $items = $this->roomService->all($request);
        return RoomResource::collection($items);

        // $items = $this->categoryService->find($id);
        // return new CategoryResource( $items);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $this->categoryService->update($request, $id);
        response()->json([
            'success' => true,
        ]);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $this->categoryService->destroy($id);
        response()->json([
            'success' => true,
        ]);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Http\Requests\StoreCategoryRequest;
use App\Http\Requests\UpdateCategoryRequest;
use App\Services\Interfaces\CategoryServiceInterface;
use Illuminate\Support\Facades\Log;

class CategoryController extends Controller
{
    protected $categoryService;
    public function __construct(CategoryServiceInterface $categoryService)
    {
        $this->categoryService = $categoryService;
    }
    public function index(Request $request)
    {
        $this->authorize('viewAny', Category::class);
        $items = $this->categoryService->all($request);
        return view('categories.index', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $this->authorize('create', Category::class);
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreCategoryRequest $request)
    {
        $this->authorize('create', Category::class);
        $data = $request->except(['_token','_method']);
        $this->categoryService->store($data);
        toast('Thêm Thành Công!', 'success', 'top-right');
        return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $this->authorize('update', Category::class);
        $item = $this->categoryService->find($id);
        return view('categories.edit', compact('item'));

    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateCategoryRequest $request,$id)
    {
        $this->authorize('update', Category::class);
        $data = $request->except(['_token','_method']);
        $this->categoryService->update($id,$data);
        toast('Sửa Thành Công!', 'success', 'top-right');
            return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        $this->authorize('delete', Category::class);
        $this->categoryService->destroy($id);
        toast('Xóa Thành Công!', 'success', 'top-right');
        return redirect()->route('categories.index');
    }
    public function getTrashed()
    {
        $this->authorize('viewtrash', Category::class);
        $items = $this->categoryService->getTrashed();
        return view('categories.trash', compact('items'));
    }
    public function restore($id)
    {
        $this->authorize('restore', Category::class);
        try {
            $items = $this->categoryService->restore($id);
            toast('Khôi Phục Thành Công!', 'success', 'top-right');
            return redirect()->route('categories.index');
        } catch (\exception $e) {
            Log::error($e->getMessage());
            toast('Có Lỗi Xảy Ra!', 'error', 'top-right');
            return redirect()->route('categories.index');
        }
    }
    public function deleteforever($id)
    {

        $this->authorize('forceDelete', Category::class);
        try {
            $items = $this->categoryService->deleteforever($id);
            toast('Xóa Vĩnh Viễn Thành Công!', 'success', 'top-right');
            return redirect()->route('categories.index');
        } catch (\exception $e) {
            Log::error($e->getMessage());
            toast('Có Lỗi Xảy Ra!', 'error', 'top-right');
            return redirect()->route('categories.index');
        }
}
}

resources/views/categories/create.blade.php
@extends('layouts.master')
@section('content')
    @include('sweetalert::alert')
    <div class="page-header">
        <h3 class="page-title">Thêm Mới Thể Loại</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                <li class="breadcrumb-item active" aria-current="page"> Thêm Mới Thể Loại </li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('categories.store') }}" method='post' enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="exampleInputName1">Tên thể loại</label>
                            <input name="name" type="text" class="form-control" placeholder="Nhập tên " value="{{ old('name') }}">
                            @error('name')
                                <p class="text text-danger ">{{ $message }}</p>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label>Ảnh</label>
                            <input type="file" name="image" class="form-control" value="{{ old('image') }}">
                            @error('image')<p class="text text-danger ">{{ $message }}</p> @enderror
                        </div>
                        <div class="d-grid">
                            <button class="btn btn-info" type="submit">Thêm</button>
                            <a href="{{ route('categories.index') }}" class="btn btn-light">Quay lại</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.master')
@section('content')
 @include('sweetalert::alert')
    <div class="page-header">
        <h3 class="page-title">Chỉnh Sửa Thể Loại</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                <li class="breadcrumb-item active" aria-current="page"> Chỉnh Sửa Thể Loại </li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <form  action="{{route('categories.update',[$item->id])}}" method="POST" enctype="multipart/form-data">
                        @method('PUT')
                        @csrf
                        <div class="form-group">
                            <label for="exampleInputName1">Tên thể loại</label>
                            <input name="name" type="text" value='{{$item->name}}' class="form-control" >
                            @error('name')
                                <p class="text text-danger ">{{ $message }}</p>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1" class="form-label">Ảnh</label>
                            <input type="file" class="form-control" name="image" value='{{$item->image}}'>
                            <img type="hidden" width="120px" height="120px" id="blah1"
                                                src="{{ $item->image}}" alt="" />
                        </div>
                        <div class="form-group">
                            <input type="submit" class="btn btn-info" value="Cập nhật" >
                            <a href="{{route('categories.index')}}" class="btn btn-light">Quay lại</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.master')
@section('content')
        @include('sweetalert::alert')
        <div class="page-header">
            <h3 class="page-title">Danh sách thể loại</h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('trangchu') }}">Trang chủ</a></li>
                    <li class="breadcrumb-item active" aria-current="page"> Danh sách thể loại </li>
                </ol>
            </nav>
        </div>
        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-header">
                        <form action="" method="get">
                            <div class="row mb-2">
                                <div class="col">
                                    @if (Auth::user()->hasPermission('Category_create'))
                                        <a href="{{ route('categories.create') }}" class="btn btn-primary"> Thêm mới </a>
                                    @endif
                                </div>
                            </div>

                            <div class="row">
                                <div class="col">
                                    <input type="text" placeholder="Nhập ID" class="form-control"
                                        value="{{ request()->id }}" name="id">
                                </div>
                                <div class="col">
                                    <input type="text" placeholder="Nhập tên" class="form-control"
                                        value="{{ request()->name }}" name="name">
                                </div>
                                <div class="col">
                                    <button type="submit" class="btn btn-info"> Tìm </button>
                                    <a href="{{ route('categories.index') }}" type="submit" class="btn btn-secondary">Đặt
                                        lại</a>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>STT</th>
                                        <th>Tên Thể loại</th>
                                        <th>Ảnh</th>
                                        <th>Hành động</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($items as $key => $item)
                                        <tr>
                                            <td>{{ ++$key }}</td>
                                            <td>{{ $item->name }}</td>
                                            <td><img
                                                style="width:120px; height:100px" src="{{ $item->image }}"
                                                alt=""></a></td>
                                            @if (Auth::user()->hasPermission('Category_update') || Auth::user()->hasPermission('Category_delete'))
                                                <td>
                                                    @if (Auth::user()->hasPermission('Category_update'))
                                                        <form action="{{ route('categories.destroy', [$item->id]) }}"
                                                            method="post">
                                                            @method('DELETE')
                                                            @csrf
                                                            <a href="{{ route('categories.edit', $item['id']) }}"
                                                                class="btn btn-info">Sửa</a>
                                                    @endif

                                                    @if (Auth::user()->hasPermission('Category_update'))
                                                        <button
                                                            onclick="return confirm('Bạn có muốn chuyển danh mục này vào thùng rác không?');"
                                                            class="btn btn-danger">Xóa</button>
                                                    @endif
                                                    </form>
                                                </td>
                                            @endif
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <nav class="float-right">
                            {{ $items->links() }}
                        </nav>
                    </div>
                </div>
            </div>
        </div>

    @endsection

resources/views/categories/trash.blade.php
@extends('layouts.master')
@section('content')
    @include('sweetalert::alert')
    <div class="page-header">
        <h3 class="page-title">Thùng rác</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                <li class="breadcrumb-item active" aria-current="page"> Thùng rác thể loại </li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-header">
                    <form action="" method="get">
                        <div class="row mb-2">
                            <div class="col">
                                <a href="{{ route('categories.index') }}" class="btn btn-primary"> Quay lại </a>
                            </div>
                        </div>

                    </form>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>STT</th>
                                    <th>Tên Thể loại</th>
                                    <th>Hành động</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($items as $key => $item)
                                    <tr>
                                        <td>{{ ++$key }}</td>
                                        <td>{{ $item->name }}</td>
                                        @if (Auth::user()->hasPermission('Category_restore') || Auth::user()->hasPermission('Category_forceDelete'))
                                            <td>
                                                @if (Auth::user()->hasPermission('Category_restore'))
                                                    <form action="{{ route('categories.deleteforever', [$item->id]) }}"
                                                        method="post">
                                                        @method('DELETE')
                                                        @csrf
                                                        <a href="{{ route('categories.restore', $item['id']) }}"
                                                            class="btn btn-info">Khôi phục</a>
                                                @endif
                                                @if (Auth::user()->hasPermission('Category_forceDelete'))

                                                    <button onclick="return confirm('Bạn có muốn Xóa vĩnh viễn không?');"
                                                        class="btn btn-danger">Xóa vĩnh viễn</button>
                                                    </form>
                                                @endif
                                            </td>
                                          @endif
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection