routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\GroupController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\UserController;
// use App\Http\Controllers\GroupController;
use Illuminate\Support\Facades\Route;
use Symfony\Component\CssSelector\XPath\Extension\FunctionExtension;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//Login
Route::get('/', [AuthController::class, 'login'])->name('login');
Route::post('/checklogin', [AuthController::class, 'postLogin'])->name('admin.checklogin');
Route::get('/forget-password', [UserController::class, 'forget_password'])->name('forget-password');
Route::post('/sendmail', [UserController::class, 'sendMail'])->name('sendmail');

Route::prefix('/')->middleware(['auth', 'preventBackHistory'])->group(function () {
    Route::get('admin', [AuthController::class, 'home'])->name('trangchu');
    Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

    // Categoryy
    Route::group(['prefix' => 'categories'], function () {
        Route::get('/trash', [CategoryController::class, 'getTrashed'])->name('categories.trash');
        Route::get('/restore/{id}', [CategoryController::class, 'restore'])->name('categories.restore');
        Route::delete('/deleteforever/{id}', [CategoryController::class, 'deleteforever'])->name('categories.deleteforever');
        });
    Route::resource('categories',\App\Http\Controllers\CategoryController::class);
   
    // Rooms
    Route::group(['prefix' => 'rooms'], function () {
        Route::get('/trash', [RoomController::class, 'getTrashed'])->name('rooms.trash');
        Route::get('/restore/{id}', [RoomController::class, 'restore'])->name('rooms.restore');
        Route::delete('/deleteforever/{id}', [RoomController::class, 'deleteforever'])->name('rooms.deleteforever');
        });
    Route::resource('rooms',\App\Http\Controllers\RoomController::class);
    //xuất file excel rooms
    Route::get('/export-rooms', [RoomController::class, 'export'])->name('rooms.export');
    // Customers
    Route::get('/customers', [CustomerController::class, 'index'])->name('customers.index');
    // Orders
    Route::group(['prefix' => 'orders'], function () {
        Route::get('/', [OrderController::class, 'index'])->name('orders.index');
        Route::get('/detail/{id}', [OrderController::class, 'show'])->name('orders.detail');
        Route::get('/create', [OrderController::class, 'create'])->name('orders.create');
        Route::post('/store', [OrderController::class, 'store'])->name('orders.store');
    });
    //xuất file excel orders
    Route::get('/export-orders', [OrderController::class, 'export'])->name('orders.export');

    Route::resource('users',\App\Http\Controllers\UserController::class);
    Route::resource('groups',\App\Http\Controllers\GroupController::class);
    Route::group(['prefix'=>'groups'], function(){
    Route::put('/updateRoles/{id}', [GroupController::class, 'updateRoles'])->name('groups.updateRoles');

});
});

app/Models/Room.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Room extends Model
{

     use HasFactory,SoftDeletes;
    protected $table ='rooms';
    protected $fillable = ['id','name','price','status','description','category_id','image'];
    public function category()
    {
        return $this->belongsTo(Category::class);
    }


}

app/Http/Controllers/Api/RoomController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreRoomRequest;
use App\Http\Requests\UpdateRoomRequest;
use Illuminate\Http\Request;
use App\Services\Interfaces\RoomServiceInterface;
use App\Http\Resources\RoomResource;

class RoomController extends Controller
{
    protected $roomService;
    public function __construct(RoomServiceInterface $roomService)
    {
        $this->roomService = $roomService;
    }
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $items = $this->roomService->all($request);
        return RoomResource::collection($items);
    }


    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreRoomRequest $request)
    {
        $data = $request->except(['_token','_method']);
        $this->roomService->store($data);
        return response()->json([
            'success' => true,
        ]);

    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $item = $this->roomService->find($id);
        return new RoomResource($item);
    }


    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateRoomRequest $request, string $id)
    {
        $data = $request->except(['_token','_method']);
        $this->roomService->update($data, $id);
        return response()->json([
            'success' => true,
        ]);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $this->roomService->destroy($id);
        response()->json([
            'success' => true,
        ]);
    }
    public function relatedItems($id,Request $request){
        $item=$this->roomService->find($id);
        $request->category_id = $item->category_id;
        $request->limit = 4;
        $request->all = 1;
        $request->id = 0;
        $items = $this->roomService->all($request);
        return RoomResource::collection($items);

    }
}

app/Http/Controllers/RoomController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreRoomRequest;
use App\Http\Requests\UpdateRoomRequest;
use App\Models\Category;
use App\Models\Room;
use App\Services\Interfaces\RoomServiceInterface;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Maatwebsite\Excel\Facades\Excel;
use App\Exports\RoomsExport;

class RoomController extends Controller
{

    protected $roomService;
    public function __construct(RoomServiceInterface $roomService)
    {
        $this->roomService = $roomService;
    }
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {

        $this->authorize('viewAny', Room::class);
        $items = $this->roomService->all($request);
        $categories = Category::get();
        return view('rooms.index', compact('items', 'categories'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $this->authorize('create', Room::class);
        $categories = Category::all();
        return view('rooms.create', compact('categories'));

    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreRoomRequest $request)
    {
        $this->authorize('create', Room::class);
        $data = $request->except(['_token','_method']);
        $this->roomService->store($data);
        toast('Thêm Mới Phòng Thành Công!', 'success', 'top-right');
        return redirect()->route('rooms.index');
    }

    /**
     * Display the specified resource.
     */
    public function show($id)
    {
        $categories = Category::get();
        $items = $this->roomService->find($id);
        return view('rooms.show', compact('items','categories'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $this->authorize('update', Room::class);
        $items = $this->roomService->find($id);
        $categories = Category::all();
        // dd($items);
        $room = $this->roomService->find($id);
        return view('rooms.edit', compact('items', 'categories', 'room'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateRoomRequest $request, $id)
    {

        $this->authorize('update', Room::class);
        $data = $request->except(['_token','_method']);
        $this->roomService->update($id,$data);
        toast('Sửa Phòng Thành Công!', 'success', 'top-right');
        return redirect()->route('rooms.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        $this->authorize('delete', Room::class);
        $items = $this->roomService->destroy($id);
        toast('Phòng Đã Được Đưa Vào Thùng Rác!', 'success', 'top-right');
        return redirect()->route('rooms.index');
    }
    public function getTrashed()
    {
        $items = $this->roomService->getTrashed();
        $softs = Room::onlyTrashed()->paginate(3);
        $categories = Category::get();
        return view('rooms.trash', compact('softs','categories'));
    }
    public function restore($id)
    {
        try {
            $items = $this->roomService->restore($id);
            toast('Khôi phục Phòng Thành Công!', 'success', 'top-right');
            return redirect()->route('rooms.index');
        } catch (\exception $e) {
            Log::error($e->getMessage());
            toast('Có Lỗi Xảy Ra!', 'error', 'top-right');
            return redirect()->route('rooms.index');
        }
    }
    public function deleteforever($id)
    {

        try {
            $items = $this->roomService->deleteforever($id);
            toast('Xóa Vĩnh Viễn Sản Phẩm Thành Công!', 'success', 'top-right');
            return redirect()->route('rooms.index');
        } catch (\exception $e) {
            Log::error($e->getMessage());
            toast('Có Lỗi Xảy Ra!', 'error', 'top-right');
            return redirect()->route('rooms.index');
        }
    }

    public function export()
    {
        return Excel::download(new RoomsExport, 'rooms.xlsx');
    }

}

resources/views/rooms/create.blade.php
@extends('layouts.master')
@section('content')
<div class="page-header">
    <h3 class="page-title">Thêm mới phòng</h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('trangchu')}}">Trang chủ</a></li>
            <li class="breadcrumb-item active" aria-current="page"> Thêm mới phòng </li>
        </ol>
    </nav>
</div>
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <form class="forms-sample" action="{{ route('rooms.store') }}" method='post' enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label for="exampleInputName1">Tên phòng</label>
                        <input type="text" class="form-control" name="name" placeholder="Tên" value="{{ old('name') }}">
                        @error('name')<p class="text text-danger ">{{ $message }}</p> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail3">Giá</label>
                        <input type="text" class="form-control" name="price" placeholder="0" value="{{ old('price') }}">
                        @error('price')<p class="text text-danger ">{{ $message }}</p> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword4">Tình trạng</label>
                        <select name="status" id="" class="form-control">
                            <option value="">--Vui lòng chọn--</option>
                            <option value="1" {{ old('status') == '1' ? 'selected' : '' }}>Còn phòng</option>
                            <option value="2" {{ old('status') == '2' ? 'selected' : '' }}>Hết phòng</option>
                        </select>
                        @error('status')<p class="text text-danger ">{{ $message }}</p> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleSelectGender">Thể loại</label>
                        <select class="form-control" name="category_id">
                            <option value="">--Vui lòng chọn--</option>
                            @foreach ($categories as $category)
                                <option value="{{ $category->id }}" {{ old('category_id') == $category->id ? 'selected' : '' }}>{{ $category->name }}</option>
                            @endforeach
                        </select>
                        @error('category_id')<p class="text text-danger ">{{ $message }}</p> @enderror
                    </div>
                    <div class="form-group">
                        <label>Ảnh</label>
                        <input type="file" name="image" class="form-control" value="{{ old('image') }}">
                        @error('image')<p class="text text-danger ">{{ $message }}</p> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleTextarea1">Mô tả</label>
                        <textarea class="form-control" rows="4" name="description" value="{{ old('description') }}"></textarea>
                        @error('description')<p class="text text-danger ">{{ $message }}</p> @enderror
                    </div>
                    <button type="submit" class="btn btn-primary mr-2"> Thêm </button>
                    <a href="{{route('rooms.index')}}" class="btn btn-warning">Quay lại</a>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/rooms/edit.blade.php
@extends('layouts.master')
@section('content')

<div class="page-header">
  <h3 class="page-title">Chỉnh sửa phòng</h3>
  <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{{route('trangchu')}}">Trang chủ</a></li>
          <li class="breadcrumb-item active" aria-current="page"> Chỉnh sửa phòng </li>
      </ol>
  </nav>
</div>
<div class="row">
  <div class="col-lg-12 grid-margin stretch-card">
      <div class="card">
          <div class="card-body">
              <form class="forms-sample" action="{{route('rooms.update',[$items->id])}}" method='post' enctype="multipart/form-data">
                @method('put')
                  @csrf
                  <div class="form-group">
                      <label for="exampleInputName1">Tên phòng</label>
                      <input type="text" class="form-control" name="name" value='{{$items->name}}'>
                      @error('name')<p class="text text-danger ">{{ $message }}</p> @enderror
                  </div>
                  <div class="form-group">
                      <label for="exampleInputEmail3">Giá</label>
                      <input type="text" class="form-control" name="price" value='{{$items->price}}'>
                      @error('price')<p class="text text-danger ">{{ $message }}</p> @enderror
                  </div>
                  <div class="form-group">
                      <label for="exampleInputPassword4">Tình trạng</label>
                      <select name="status" class="form-control">
                        <option value="1" {{ $items->status == 1 ? 'selected' : '' }}>Còn phòng</option>
                        <option value="2" {{ $items->status == 2 ? 'selected' : '' }}>Hết phòng</option>
                    </select>
                  </div>
                  <div class="form-group">
                      <label for="exampleSelectGender">Thể loại</label>
                      <select class="form-control" name="category_id">
                          @foreach ($categories as $category)
                          <option
                                  <?= $category->id == $items->category_id ? 'selected' : '' ?>
                                  value="{{ $category->id }}">
                                  {{ $category->name }}</option>
                          @endforeach
                      </select>
                  </div>
                  <div class="form-group">
                      <label>Ảnh</label>
                      <input type="file" name="image" class="form-control" value='{{$items->image}}'>
                      <img type="hidden" width="120px" height="120px" id="blah1" src="{{$items->image }}" alt="" />
                  </div>
                  <div class="form-group">
                      <label for="exampleTextarea1">Mô tả</label>
                      <textarea class="form-control" rows="4" name="description">{{$items->description}}</textarea>
                      @error('description')<p class="text text-danger ">{{ $message }}</p> @enderror
                  </div>
                  <input type="submit" value="Cập nhật" class="btn btn-primary">
                  <a href="{{route('rooms.index')}}" class="btn btn-warning">Quay lại</a>
              </form>
          </div>
      </div>
  </div>
</div>
@endsection

resources/views/rooms/index.blade.php
@extends('layouts.master')
@section('content')
    @include('sweetalert::alert')
    <div class="page-header">
        <h3 class="page-title">Danh sách phòng</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('trangchu') }}">Trang chủ</a></li>
                <li class="breadcrumb-item active" aria-current="page"> Quản lý phòng </li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-header">
                    <form action="" method="get">
                        <div class="row mb-2">
                            <div class="col">
                                @if (Auth::user()->hasPermission('room_create'))
                                    <a href="{{ route('rooms.create') }}" class="btn btn-primary"> Thêm mới </a>
                                @endif
                                <a href="{{ route('rooms.export') }}" class="btn btn-warning">Xuất excel</a>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col">
                                <input type="text" placeholder="Nhập ID" class="form-control" value="{{ request()->id }}"
                                    name="id">
                            </div>
                            <div class="col">
                                <input type="text" placeholder="Nhập tên" class="form-control"
                                    value="{{ request()->name }}" name="name">
                            </div>
                            <div class="col">
                                <select class="form-control" name="category_id">
                                    <option value="">Tất cả danh mục</option>
                                    @foreach ($categories as $category)
                                        <option @selected(request()->category_id == $category->id) value="{{ $category->id }}">
                                            {{ $category->name }} </option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col">
                                <button type="submit" class="btn btn-info"> Tìm </button>
                                <a href="{{ route('rooms.index') }}" type="submit" class="btn btn-secondary">Đặt lại</a>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>STT</th>
                                    <th>Hình ảnh</th>
                                    <th>Mã phòng</th>
                                    <th>Giá</th>
                                    <th>Tình trạng</th>
                                    <th>Thể loại phòng</th>
                                    <th>Hành động</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($items as $key => $item)
                                    <tr>
                                        <td>{{ ++$key }}</td>
                                        <td class="py-1">
                                            <a href="{{ route('rooms.show', $item['id']) }}">
                                                <img src="{{ $item->image }}" alt="image">
                                            </a>
                                        </td>
                                        <td>{{ $item->name }}</td>
                                        <td>{{ number_format($item->price) }} VND</td>
                                        <td>{{ $item->status == 1 ? 'Còn phòng' : 'Hết phòng' }}</td>
                                        <td> @if ($item->category)
                                            {{ $item->category->name }}
                                        @else
                                            Thể loại không tồn tại
                                        @endif</td>
                                        @if (Auth::user()->hasPermission('room_update') || Auth::user()->hasPermission('room_delete'))
                                            <td>
                                                @if (Auth::user()->hasPermission('room_update'))
                                                <form action="{{ route('rooms.destroy', [$item->id]) }}" method="post">
                                                    @method('DELETE')
                                                    @csrf
                                                    <a href="{{ route('rooms.edit', [$item->id]) }}"
                                                        class="btn btn-info">Sửa</a>
                                                @endif
                                                @if (Auth::user()->hasPermission('room_delete'))
                                                    <button
                                                        onclick="return confirm('Bạn có muốn chuyển danh mục này vào thùng rác không?');"
                                                        class="btn btn-danger">Xóa</button>
                                                @endif
                                                </form>
                                            </td>
                                        @endif
                                @endforeach
                                </tr>

                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <nav class="float-right">
                        {{ $items->appends(request()->all())->links() }}
                    </nav>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/rooms/show.blade.php
@extends('layouts.master')
@section('content')
<div class="page-header">
    <h3 class="page-title">Chi tiết phòng </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('trangchu')}}">Trang chủ</a></li>
            <li class="breadcrumb-item active" aria-current="page"> Chi tiết phòng </li>
        </ol>
    </nav>
</div>
<div class="card">
    <div class="card-body">
        <div class="row g-0">
            <div class="col-md-6">
                <div class="d-flex flex-column justify-content-center">
                    <div style=" margin-top: 24px;" class="main_image">
                        <img src="{{ $items->image }}" id="main_product_image" height="360" width="462">
                    </div><br>
                </div>
            </div>
            <div class="col-md-6">
                <div class="p-3 right-side">
                    <div class="product-info-tabs">
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active profile-overview" id="profile-overview">
                                <table class="table table-striped">
                                    <tbody>
                                        <tr>
                                            <td>ID</td>
                                            <td>{{ $items->id }}</td>
                                        </tr>
                                        <tr>
                                            <td>Tên phòng</td>
                                            <td>{{ $items->name }}</td>
                                        </tr>
                                        <tr>
                                            <td>Giá</td>
                                            <td>{{number_format($items->price)}} vnd</td>
                                        </tr>
                                        <tr>
                                            <td>Tình trạng</td>
                                            <td>{{ $items->status == 1 ? 'Còn phòng' : 'Hết phòng' }}</td>
                                        </tr>
                                        <tr>
                                            <td>Mô tả</td>
                                            <td>{!! wordwrap($items->description, 70, "<br>", true) !!}</td>

                                        </tr>
                                    </tbody>
                                </table> 
                                <br>
                                <a href="{{ route('rooms.index') }}" class="btn btn-primary">Quay lại</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/rooms/trash.blade.php
@extends('layouts.master')
@section('content')

<div class="page-header">
    <h3 class="page-title">Thùng rác</h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('trangchu')}}">Trang chủ</a></li>
            <li class="breadcrumb-item active" aria-current="page"> Thùng rác phòng </li>
        </ol>
    </nav>
</div>
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-header">
                    <div class="row mb-2">
                        <div class="col">
                            <a href="{{route('rooms.index')}}" class="btn btn-primary"> Quay lại </a>
                        </div>
                    </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>STT</th>
                                <th>Hình ảnh</th>
                                <th>Tên</th>
                                <th>Giá</th>
                                <th>Tình trạng</th>
                                <th>Thể loại</th>
                                <th>Hành động</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($softs  as $key => $item)
                            <tr>
                                <td>{{++$key}}</td>
                                <td class="py-1">
                                    <a href="{{route('rooms.show',$item['id'])}}">
                                        <img src="{{ $item->image }}" alt="image">
                                    </a>
                                </td>
                                <td>{{$item->name}}</td>
                                <td>{{number_format( $item->price) }} VND</td>
                                <td>{{ $item->status == 1 ? 'Còn phòng' : 'Hết phòng' }}</td>
                                <td>{{$item->category ->name}}</td>
                                <td>
                                    <form action="{{route('rooms.deleteforever',[$item->id])}}" method="post">
                                        @method('DELETE')
                                        @csrf
                                        <a href="{{route('rooms.restore',[$item->id])}}" class="btn btn-info">Khôi phục</a>
                                        <button onclick="return confirm('Bạn có chắc chắn muốn xóa không?');"
                                            class="btn btn-danger">Xóa</button>
                                    </form>
                                </td>
                                @endforeach
                            </tr>
                            
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <nav class="float-right">
                    {{ $softs->links() }}
                  </nav>
            </div>
        </div>
    </div>
</div>
@endsection