routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\GroupController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\UserController;
// use App\Http\Controllers\GroupController;
use Illuminate\Support\Facades\Route;
use Symfony\Component\CssSelector\XPath\Extension\FunctionExtension;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//Login
Route::get('/', [AuthController::class, 'login'])->name('login');
Route::post('/checklogin', [AuthController::class, 'postLogin'])->name('admin.checklogin');
Route::get('/forget-password', [UserController::class, 'forget_password'])->name('forget-password');
Route::post('/sendmail', [UserController::class, 'sendMail'])->name('sendmail');

Route::prefix('/')->middleware(['auth', 'preventBackHistory'])->group(function () {
    Route::get('admin', [AuthController::class, 'home'])->name('trangchu');
    Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

    // Categoryy
    Route::group(['prefix' => 'categories'], function () {
        Route::get('/trash', [CategoryController::class, 'getTrashed'])->name('categories.trash');
        Route::get('/restore/{id}', [CategoryController::class, 'restore'])->name('categories.restore');
        Route::delete('/deleteforever/{id}', [CategoryController::class, 'deleteforever'])->name('categories.deleteforever');
        });
    Route::resource('categories',\App\Http\Controllers\CategoryController::class);
   
    // Rooms
    Route::group(['prefix' => 'rooms'], function () {
        Route::get('/trash', [RoomController::class, 'getTrashed'])->name('rooms.trash');
        Route::get('/restore/{id}', [RoomController::class, 'restore'])->name('rooms.restore');
        Route::delete('/deleteforever/{id}', [RoomController::class, 'deleteforever'])->name('rooms.deleteforever');
        });
    Route::resource('rooms',\App\Http\Controllers\RoomController::class);
    //xuất file excel rooms
    Route::get('/export-rooms', [RoomController::class, 'export'])->name('rooms.export');
    // Customers
    Route::get('/customers', [CustomerController::class, 'index'])->name('customers.index');
    // Orders
    Route::group(['prefix' => 'orders'], function () {
        Route::get('/', [OrderController::class, 'index'])->name('orders.index');
        Route::get('/detail/{id}', [OrderController::class, 'show'])->name('orders.detail');
        Route::get('/create', [OrderController::class, 'create'])->name('orders.create');
        Route::post('/store', [OrderController::class, 'store'])->name('orders.store');
    });
    //xuất file excel orders
    Route::get('/export-orders', [OrderController::class, 'export'])->name('orders.export');

    Route::resource('users',\App\Http\Controllers\UserController::class);
    Route::resource('groups',\App\Http\Controllers\GroupController::class);
    Route::group(['prefix'=>'groups'], function(){
    Route::put('/updateRoles/{id}', [GroupController::class, 'updateRoles'])->name('groups.updateRoles');

});
});

resources/views/includes/footer.blade.php
<footer class="footer">
  <div class="d-sm-flex justify-content-center justify-content-sm-between">
    <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright ©
      bootstrapdash.com
      2023</span>
    <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Free <a
        href="https://www.bootstrapdash.com/" target="_blank">Bootstrap dashboard template</a>
      from
      Bootstrapdash.com</span>
  </div>
</footer>

resources/views/includes/header.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Breeze Admin</title>
    <link rel="stylesheet" href="{{asset('assets/vendors/mdi/css/materialdesignicons.min.css')}}" />
    <link rel="stylesheet" href="{{asset('assets/vendors/flag-icon-css/css/flag-icon.min.css')}}" />
    <link rel="stylesheet" href="{{asset('assets/vendors/css/vendor.bundle.base.css')}}" />
    <link rel="stylesheet" href="{{asset('assets/vendors/font-awesome/css/font-awesome.min.css')}}" />
    <link rel="stylesheet" href="{{asset('assets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.css')}}" />
    <link rel="stylesheet" href="{{asset('assets/css/style.css')}}" />
    <link rel="shortcut icon" href="{{asset('assets/images/favicon.png')}}" />
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  </head>
  <body>
    <div class="container-scroller">

resources/views/includes/nav.blade.php
<nav class="navbar col-lg-12 col-12 p-lg-0 fixed-top d-flex flex-row">
    <div class="navbar-menu-wrapper d-flex align-items-stretch justify-content-between">
        <a class="navbar-brand brand-logo-mini align-self-center d-lg-none" href="index.html"><img
                src="{{asset('assets/images/logo-mini.svg')}}" alt="logo" /></a>
        <button class="navbar-toggler navbar-toggler align-self-center mr-2" type="button"
            data-toggle="minimize">
            <i class="mdi mdi-menu"></i>
        </button>
        <ul class="navbar-nav navbar-nav-right ml-lg-auto">
            <li class="nav-item nav-profile dropdown border-0">
                <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-toggle="dropdown">
                    <img class="nav-profile-img mr-2" alt="" src="{{asset(auth()->user()->image)}}" />
                    <span class="profile-name">{{auth()->user()->name}}</span>
                </a>
                <div class="dropdown-menu navbar-dropdown w-100" aria-labelledby="profileDropdown">
                    <a class="dropdown-item" href="{{route('logout')}}">
                        <i class="mdi mdi-logout mr-2 text-primary"></i> Đăng xuất </a>
                </div>
            </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
            data-toggle="offcanvas">
            <span class="mdi mdi-menu"></span>
        </button>
    </div>
</nav>

resources/views/includes/sidebar.blade.php
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <div class="text-center sidebar-brand-wrapper d-flex align-items-center">
      <a class="sidebar-brand brand-logo" href="{{route('login')}}"><img src="{{asset('assets/images/sky-logo.png')}}"
          alt="logo" /></a>
      <a class="sidebar-brand brand-logo-mini pl-4 pt-3" href=""><img
          src="{{asset('assets/images/logo-mini.svg')}}" alt="logo" /></a>
    </div>
    <ul class="nav">
      <li class="nav-item nav-profile">
        <a href="#" class="nav-link">
          <div class="nav-profile-image">
            <img src="{{asset(auth()->user()->image)}}" alt="profile" />
            <span class="login-status online"></span>
            <!--change to offline or busy as needed-->
          </div>
          <div class="nav-profile-text d-flex flex-column pr-3">
            <span class="font-weight-medium mb-2">{{auth()->user()->name}}</span>
            <span class="font-weight-normal">{{auth()->user()->group->name}}</span>
          </div>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{route('login')}}">
          <i class="mdi mdi-home menu-icon"></i>
          <span class="menu-title">Trang chủ</span>
        </a>
      </li>
      <li class="nav-item">
        @if (Auth::user()->hasPermission('Category_viewAny'))
          <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false"
            aria-controls="ui-basic">
            <i class="mdi mdi-crosshairs-gps menu-icon"></i>
            <span class="menu-title">Quản lý Thể loại</span>
            <i class="menu-arrow"></i>
          </a>
          <div class="collapse" id="ui-basic">
            <ul class="nav flex-column sub-menu">
              <li class="nav-item">
                <a class="nav-link" href="{{route('categories.index')}}">Danh sách</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{route('categories.trash')}}">Thùng rác</a>
              </li>
            </ul>
          </div>
          @endif
        </li>
      <li class="nav-item">
        @if (Auth::user()->hasPermission('room_viewAny'))
        <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false"
          aria-controls="ui-basic">
          <i class="mdi mdi-table-large menu-icon"></i>
          <span class="menu-title">Quản lý phòng</span>
          <i class="menu-arrow"></i>
        </a>
        <div class="collapse" id="ui-basic">
          <ul class="nav flex-column sub-menu">
            <li class="nav-item">
              <a class="nav-link" href="{{route('rooms.index')}}">Danh sách</a>
            </li>
            <li class="nav-item">
                @if (Auth::user()->hasPermission('room_trash'))
              <a class="nav-link" href="{{route('rooms.trash')}}">Thùng rác</a>
              @endif
            </li>
          </ul>
        </div>
        @endif
      </li>
      <li class="nav-item">
        @if (Auth::user()->hasPermission('Group_viewAny'))
          <a class="nav-link" href="{{route('groups.index')}}">
            <i class="mdi mdi-contacts menu-icon"></i>
            <span class="menu-title">Quản lý phân quyền  </span>
          </a>
          @endif
      </li>
      <li class="nav-item">
        @if (Auth::user()->hasPermission('User_viewAny'))
        <a class="nav-link" href="{{route('users.index')}}">
          <i class="mdi mdi-contacts menu-icon"></i>
          <span class="menu-title">Quản lý nhân viên </span>
        </a>
          @endif
      </li>
      <li class="nav-item">
        @if (Auth::user()->hasPermission('Customer_viewAny'))
          <a class="nav-link" href="{{route('customers.index')}}">
            <i class="mdi mdi-contacts menu-icon"></i>
            <span class="menu-title">Quản lý khách hàng</span>
          </a>
          @endif
      </li>
      <li class="nav-item">
        @if (Auth::user()->hasPermission('Order_viewAny'))
        <a class="nav-link" href="{{route('orders.index')}}">
          <i class="mdi mdi-chart-bar menu-icon"></i>
          <span class="menu-title">Quản lý đơn đặt phòng</span>
        </a>
        @endif
      </li>
    </ul>
  </nav>